services:
  #############################
  ##
  ##  EXAMPLE
  ##
  ############################
  article.search:
    class: SearchBundle\Services\SearchService
    arguments:
      - "@fos_elastica.manager.orm"
      - %easy_search_bundle.elastica_entity%
      - ['%easy_search_bundle.search_string%']
    calls:
      - [addFilter, ['@elastic.search.filter.enabled']]
      - [addAggregation, ['@elastic.search.aggregation.categories']]
